import { IFormStep } from '../types/dashboard_recipe.types';

// Steps array
export const formSteps: IFormStep[] = [
  { label: 'Basic Info', isDisabled: false },
  { label: 'Details', isDisabled: false },
  { label: 'Nutritional Facts', isDisabled: false },
  { label: 'Directions', isDisabled: false },
  { label: 'Preview', isDisabled: false },
];

// nutrients measurement units

export const measurementUnits = [
  { label: 'Grams (g)', value: 'g' },
  { label: 'Milligrams (mg)', value: 'mg' },
  { label: 'Micrograms (mcg)', value: 'mcg' },
  { label: 'Kilocalories (kcal)', value: 'kcal' },
  { label: 'Calories (cal)', value: 'cal' },
  { label: 'Percent (%)', value: '%' },
  { label: 'Milliliters (ml)', value: 'ml' },
  { label: 'Liters (l)', value: 'l' },
  { label: 'Teaspoons (tsp)', value: 'tsp' },
  { label: 'Tablespoons (tbsp)', value: 'tbsp' },
  { label: 'Cups', value: 'cups' },
  { label: 'Ounces (oz)', value: 'oz' },
  { label: 'Fluid Ounces (fl oz)', value: 'fl oz' },
  { label: 'Pints (pt)', value: 'pt' },
  { label: 'Quarts (qt)', value: 'qt' },
  { label: 'Gallons (gal)', value: 'gal' },
  { label: 'Pieces', value: 'pieces' },
];

export const tags = [
  '10 ingredients or less',
  '15 minutes or less',
  '60 minutes or less',
  'appetizer',
  'Autumn',
  'bacon',
  'bake',
  'basil',
  'bbb',
  'BBQ',
  'Carbs',
  'cheese',
  'Dairy-free',
  'Dessert',
  'Dip',
  'Easy',
  'Fall',
  'Fast-Food',
  'Gluten',
  'Gluten-Free',
  'Italian cuisine',
  'Latin-inspired',
  'Lunch',
  'Meat',
  'Mexican-inspired',
  'Milk',
  'No-bake',
  'Nut-free',
  'Oil',
  'Oil-free',
  'Olive Oil',
  'One bowl',
  'Pasta',
  'Protein',
  'Raw',
  'Recipes',
  'Refined sugar-free',
  'Sauce',
  'Snacks',
  'Soup',
  'Soy-free',
  'Spring',
  'Summer',
  'Tips and Tricks',
  'Thai',
  'Trans Fat',
  'Vegan',
  'Vegetables',
  'Veggies',
];

export const categories= [
  'Popular',
  'Pizza',
  'Meat',
  'Lunch',
  'Greens',
  'Desserts',
  'Snacks',
  'Waffles',
  'Breakfast',
  'Cakes',
  'Fast To Make',
  'Grains',
  'Pies',
  'Sweets',
  'Dinner',
];

export const durations = [
  '5 Minutes',
  '10 Minutes',
  '15 Minutes',
  '30 Minutes',
  '45 Minutes',
  '60 Minutes',
  '60+ Minutes',
];

export const servings = ['1', '5', '10', '10+'];
export const levels = ['Easy', 'Medium', 'Hard'];
